[project]
name = "lattice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "langgraph",
    "neo4j",
    "neo4j-graphrag",
    "pydantic",
    "streamlit",
]
